### PR TITLE
Dependencies update

### PR DESCRIPTION
**Pull request by Kameshwaran**
This pull request contains,

* Removed duplicate gems
* Updated the versions of the dependencies
* Updated the Gem version

### CODE REVIEW

**Comment by Charizard** [comment]
Bingo :+1: !!

**Comment by nithinkrishna** [comment]
:+1:

**Comment by Kameshwaran** [comment]
:) @Yuva / @Nithin who has the access to push the gem?

**Comment by nithinkrishna** [comment]
Anyone within the Codebrahma organization should be able to push

Regards,

Nithin Krishna

+1-323-690-3537

Linkedin <https://in.linkedin.com/pub/nithin-krishna/69/809/3a9> | Github
<https://github.com/nithinkrishna> | Blog <http://nithinkrishna.github.io/>

**Comment by Kameshwaran** [comment]
No dude. It says 'Permission denied'. I think sarkar must have it.

**Comment by Charizard** [comment]
I think it's me. Gimme a min. let me see if I can add you. In the mean while can you create an account with rubygems.org?

**Comment by Kameshwaran** [comment]
Already created one. Handle: Kameshwaran

**Comment by Charizard** [comment]
Sorry, I only have access to `factory_group`. It should be @nithinkrishna who has the access.

**Comment by Kameshwaran** [comment]
@nithinkrishna please check your account dude :)

**Pull request merged**
